name: Test Git Commit Hash

on:
  push:
    branches: [ main ]  # change if using another branch

jobs:
  print-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Print latest commit hash
      run: python test.py
