name: Visual Test Trigger

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Visual Test
        run: echo "Visual test triggered on push to main branch."
