name: Visual Test

on:
  push:
    branches: [main]

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r visual_tests/requirements.txt
          python -m playwright install --with-deps

      - name: Run visual test and capture multiple page screenshots
        run: |
          echo "Starting visual test for commit $GITHUB_SHA"
          python visual_tests/visual_test.py $GITHUB_SHA
          echo "Capture complete"

      - name: Push all screenshots to visual-baselines branch
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "vt-bot"
          git config --global user.email "vt-bot@example.com"

          git clone https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} baseline-repo
          cd baseline-repo

          git checkout visual-baselines || git checkout -b visual-baselines

          mkdir -p baselines/${{ github.sha }}
          cp ../visual_tests/baseline/${{ github.sha }}/*.png baselines/${{ github.sha }}/

          git add baselines/
          git commit -m "Add baseline screenshots for commit ${{ github.sha }}"
          git push origin visual-baselines
